### ISSUE TITLE
1-Change App Icon and App Name

### ISSUE THREAD

**Issue by NurhayatYurtaslan** [NurhayatYurtaslan/super_note_app#1]

**Comment by NurhayatYurtaslan** [comment]
- [x] Logo Design (size: 1024*1024)
- [x] Add flutter_launcher_icons package (dev_dependencies)
- [x] Add Pubsec.yaml (dev dependencies)
 ```
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  image_path: assets/images/logo.png
```
- [x] run terminal
`flutter pub get`
`flutter pub run flutter_launcher_icons`
